### ISSUE TITLE
Battery script not daemonized?

### ISSUE THREAD

**Issue by AhmedAA** [brennovich/my-favorite-things#4]
Hey!

Really like your battery script, but I can't seem to make it run in a daemonized state?
What have you done other than adding it to your i3 config?

Or is it as intended?

Thanks a lot for the script btw, really appreciate it :)

**Comment by AhmedAA** [comment]
Added a while true loop and a sleep statement.
Seems like an ugly solution.. still interested in hearing your thoughts :)

```bash
#!/bin/bash
#
# Concatenate multiple battery uevent reports into one
#
# uevent sample report:
#
# POWER_SUPPLY_NAME=BAT0
# POWER_SUPPLY_STATUS=Unknown
# POWER_SUPPLY_PRESENT=1
# POWER_SUPPLY_TECHNOLOGY=Li-poly
# POWER_SUPPLY_CYCLE_COUNT=0
# POWER_SUPPLY_VOLTAGE_MIN_DESIGN=11250000
# POWER_SUPPLY_VOLTAGE_NOW=11082000
# POWER_SUPPLY_POWER_NOW=0
# POWER_SUPPLY_ENERGY_FULL_DESIGN=23510000
# POWER_SUPPLY_ENERGY_FULL=23050000
# POWER_SUPPLY_ENERGY_NOW=1240000
# POWER_SUPPLY_CAPACITY=5
# POWER_SUPPLY_CAPACITY_LEVEL=Normal
# POWER_SUPPLY_MODEL_NAME=00HW022
# POWER_SUPPLY_MANUFACTURER=SANYO
# POWER_SUPPLY_SERIAL_NUMBER= 1201

mkdir -p $HOME/.my-favorite-things

parse_uevent='
{
  split($0,a,"=");
  split(a[2],b," ");

  if (a[3] == b[1])
    $5 = a[3]
  else
    switch (a[1]) {
    case "POWER_SUPPLY_NAME":
      $5 = "BAT0"
      break
    case "POWER_SUPPLY_TECHNOLOGY":
      $5 = "Li-poly"
      break
    case "POWER_SUPPLY_MANUFACTURER":
      $5 = "SANYO"
      break
    case /POWER_SUPPLY_MODEL_NAME|POWER_SUPPLY_SERIAL_NUMBER/:
      $5 = a[3] "/" b[1]
      break
    case "POWER_SUPPLY_STATUS":
      if (a[3] == "Charging" || b[1] == "Charging") $5 = "Charging";
      if (a[3] == "Unknown") $5 = b[1];
      if (b[1] == "Unknown") $5 = a[3];
      break
    case "?":
      default: $5 = (a[3] + b[1]) / 2;
      break
    };

  print a[1] "=" $5;
}
'
while true
do
  paste /sys/class/power_supply/BAT{0..1}/uevent \
    | awk "$parse_uevent" \
    > $HOME/.my-favorite-things/dual-battery-uevent

  sleep 5
```

**Comment by brennovich** [comment]
Sorry @AhmedAA only now I saw your issue, apparently my notifications weren't on for this repo.

As this script it's only informative I decided that it's not its responsibility to handle daemonization, instead my panel is responsible for it:

![panel with status](https://user-images.githubusercontent.com/379894/27255451-ff6ccd42-5374-11e7-928d-bf94f984b163.png)

As you can see there is the battery info :)

All panel code is here: https://github.com/brennovich/my-favorite-things/blob/master/templates/dotfiles/bin/panel

Inside it I have a complementary battery script to format the info as I please, and also all the infrastructure of a daemon using `fifo` to write/read each info.

The way you did with `while true` is more than fine, though :) The only real advantage I have with my approach is to have a custom sleep for each info which can save battery juice in long term.

**Comment by AhmedAA** [comment]
@brennovich thanks for your answer!
From my all my research, you might be interested in knowing that in the more recent versions of i3bar, it SHOULD have built-in support for multiple batteries :P I can't really test and confirm at the moment, as I am running Elementary OS with pantheon on my new machine.

Another issue I did have though, was (still is actually, even with Pantheon) that linux reaches a threshold at (86% on my old, 79% on my new) a percentage, and then just sits still. In the background it is still charging, but it just stays stuck until it has fully charged one of the batteries, and then it continues counting the percentage up.

Lastly, when it does this stuck thing, the timer also keeps counting up. Meaning for example, the battery reaches 86% and gets stuck. The approximate time until completely charged then just keeps counting up (I think I had it reaching 10 hours or so), and when it completes the charging of that one battery, it then goes back to showing a realistic timebox.

Oh well, obviously not something I expect you to spend time on, I was too lazy myself, just some observations!
Still a very neat solutions, and I love it!

All the best :)

**Comment by brennovich** [comment]
@AhmedAA I'm no longer using `i3wm`, I'm usin g`2bwm` instead. It's a very very lightwight wm, thats why I use my own panel ;)

> Another issue I did have though, was (still is actually, even with Pantheon) that linux reaches a threshold at (86% on my old, 79% on my new) a percentage, and then just sits still. In the background it is still charging, but it just stays stuck until it has fully charged one of the batteries, and then it continues counting the percentage up.

Do you use TLP https://wiki.archlinux.org/index.php/TLP ? If so you may be using it with default config whichs has batteries thresholds: http://linrunner.de/en/tlp/docs/tlp-configuration.html#chargethresholds
